# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: objects.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cadent.pb import repr_pb2 as cadent_dot_server_dot_repr_dot_repr__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='objects.proto',
  package='indexer',
  syntax='proto3',
  serialized_pb=_b('\n\robjects.proto\x12\x07indexer\x1a\x1d\x63\x61\x64\x65nt/server/repr/repr.proto\x1a-github.com/gogo/protobuf/gogoproto/gogo.proto\"\x85\x02\n\x0eMetricFindItem\x12\x12\n\x04text\x18\x01 \x01(\tR\x04text\x12\x1e\n\nexpandable\x18\x02 \x01(\rR\nexpandable\x12\x12\n\x04leaf\x18\x03 \x01(\rR\x04leaf\x12\x12\n\x04path\x18\x04 \x01(\tR\x04path\x12$\n\rallowChildren\x18\x05 \x01(\rR\rallowChildren\x12\x0e\n\x02id\x18\x06 \x01(\tR\x02id\x12\x1a\n\x08uniqueId\x18\x07 \x01(\tR\x08uniqueid\x12\x1d\n\x04tags\x18\r \x03(\x0b\x32\t.repr.TagR\x04tags\x12&\n\x08metaTags\x18\x0e \x03(\x0b\x32\t.repr.TagR\tmeta_tags\"#\n\x10MetricExpandItem\x12\x0f\n\x07results\x18\x02 \x03(\t\"Q\n\rMetricTagItem\x12\n\n\x02id\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\r\n\x05value\x18\x04 \x01(\t\x12\x17\n\x06isMeta\x18\x05 \x01(\x08R\x07is_metaB\x18\xc8\xe1\x1e\x00\xc0\xe2\x1e\x01\xd0\xe2\x1e\x01\xc8\xe2\x1e\x01\xe0\xe2\x1e\x01\xf8\xe1\x1e\x01\x62\x06proto3')
  ,
  dependencies=[cadent_dot_server_dot_repr_dot_repr__pb2.DESCRIPTOR])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_METRICFINDITEM = _descriptor.Descriptor(
  name='MetricFindItem',
  full_name='indexer.MetricFindItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='indexer.MetricFindItem.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, json_name='text'),
    _descriptor.FieldDescriptor(
      name='expandable', full_name='indexer.MetricFindItem.expandable', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, json_name='expandable'),
    _descriptor.FieldDescriptor(
      name='leaf', full_name='indexer.MetricFindItem.leaf', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, json_name='leaf'),
    _descriptor.FieldDescriptor(
      name='path', full_name='indexer.MetricFindItem.path', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, json_name='path'),
    _descriptor.FieldDescriptor(
      name='allowChildren', full_name='indexer.MetricFindItem.allowChildren', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, json_name='allowChildren'),
    _descriptor.FieldDescriptor(
      name='id', full_name='indexer.MetricFindItem.id', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, json_name='id'),
    _descriptor.FieldDescriptor(
      name='uniqueId', full_name='indexer.MetricFindItem.uniqueId', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, json_name='uniqueid'),
    _descriptor.FieldDescriptor(
      name='tags', full_name='indexer.MetricFindItem.tags', index=7,
      number=13, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, json_name='tags'),
    _descriptor.FieldDescriptor(
      name='metaTags', full_name='indexer.MetricFindItem.metaTags', index=8,
      number=14, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, json_name='meta_tags'),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=105,
  serialized_end=366,
)


_METRICEXPANDITEM = _descriptor.Descriptor(
  name='MetricExpandItem',
  full_name='indexer.MetricExpandItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='results', full_name='indexer.MetricExpandItem.results', index=0,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=368,
  serialized_end=403,
)


_METRICTAGITEM = _descriptor.Descriptor(
  name='MetricTagItem',
  full_name='indexer.MetricTagItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='indexer.MetricTagItem.id', index=0,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='indexer.MetricTagItem.name', index=1,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='indexer.MetricTagItem.value', index=2,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='isMeta', full_name='indexer.MetricTagItem.isMeta', index=3,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, json_name='is_meta'),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=405,
  serialized_end=486,
)

_METRICFINDITEM.fields_by_name['tags'].message_type = cadent_dot_server_dot_repr_dot_repr__pb2._TAG
_METRICFINDITEM.fields_by_name['metaTags'].message_type = cadent_dot_server_dot_repr_dot_repr__pb2._TAG
DESCRIPTOR.message_types_by_name['MetricFindItem'] = _METRICFINDITEM
DESCRIPTOR.message_types_by_name['MetricExpandItem'] = _METRICEXPANDITEM
DESCRIPTOR.message_types_by_name['MetricTagItem'] = _METRICTAGITEM

MetricFindItem = _reflection.GeneratedProtocolMessageType('MetricFindItem', (_message.Message,), dict(
  DESCRIPTOR = _METRICFINDITEM,
  __module__ = 'objects_pb2'
  # @@protoc_insertion_point(class_scope:indexer.MetricFindItem)
  ))
_sym_db.RegisterMessage(MetricFindItem)

MetricExpandItem = _reflection.GeneratedProtocolMessageType('MetricExpandItem', (_message.Message,), dict(
  DESCRIPTOR = _METRICEXPANDITEM,
  __module__ = 'objects_pb2'
  # @@protoc_insertion_point(class_scope:indexer.MetricExpandItem)
  ))
_sym_db.RegisterMessage(MetricExpandItem)

MetricTagItem = _reflection.GeneratedProtocolMessageType('MetricTagItem', (_message.Message,), dict(
  DESCRIPTOR = _METRICTAGITEM,
  __module__ = 'objects_pb2'
  # @@protoc_insertion_point(class_scope:indexer.MetricTagItem)
  ))
_sym_db.RegisterMessage(MetricTagItem)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\310\341\036\000\300\342\036\001\320\342\036\001\310\342\036\001\340\342\036\001\370\341\036\001'))
# @@protoc_insertion_point(module_scope)
