# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: repr.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()



DESCRIPTOR = _descriptor.FileDescriptor(
  name='repr.proto',
  package='repr',
  syntax='proto3',
  serialized_pb=_b('\n\nrepr.proto\x12\x04repr\x1a-github.com/gogo/protobuf/gogoproto/gogo.proto\"\"\n\x03Tag\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"\xe5\x01\n\x08StatName\x12\x0b\n\x03key\x18\x01 \x01(\t\x12&\n\x08uniqueId\x18\x02 \x01(\x04\x42\x14\xe2\xde\x1f\x0cXXX_uniqueId\xea\xde\x1f\x00\x12,\n\x0buniqueIdstr\x18\x03 \x01(\tB\x17\xe2\xde\x1f\x0fXXX_uniqueIdstr\xea\xde\x1f\x00\x12\x12\n\nresolution\x18\x04 \x01(\r\x12\x0b\n\x03ttl\x18\x05 \x01(\r\x12\x1e\n\x07tagMode\x18\x06 \x01(\x0e\x32\r.repr.TagMode\x12\x17\n\x04tags\x18\r \x03(\x0b\x32\t.repr.Tag\x12\x1c\n\tmeta_tags\x18\x0e \x03(\x0b\x32\t.repr.Tag\"z\n\x08StatRepr\x12\x1c\n\x04name\x18\x01 \x01(\x0b\x32\x0e.repr.StatName\x12\x0c\n\x04time\x18\x02 \x01(\x03\x12\x0b\n\x03min\x18\x03 \x01(\x01\x12\x0b\n\x03max\x18\x04 \x01(\x01\x12\x0c\n\x04last\x18\x05 \x01(\x01\x12\x0b\n\x03sum\x18\x06 \x01(\x01\x12\r\n\x05\x63ount\x18\x07 \x01(\x03* \n\x07TagMode\x12\x0c\n\x08METRICS2\x10\x00\x12\x07\n\x03\x41LL\x10\x01\x42\x18\xc8\xe1\x1e\x00\xc0\xe2\x1e\x01\xd0\xe2\x1e\x01\xc8\xe2\x1e\x01\xe0\xe2\x1e\x01\xf8\xe1\x1e\x01\x62\x06proto3')
  ,
  dependencies=[])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_TAGMODE = _descriptor.EnumDescriptor(
  name='TagMode',
  full_name='repr.TagMode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='METRICS2', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ALL', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=459,
  serialized_end=491,
)
_sym_db.RegisterEnumDescriptor(_TAGMODE)

TagMode = enum_type_wrapper.EnumTypeWrapper(_TAGMODE)
METRICS2 = 0
ALL = 1



_TAG = _descriptor.Descriptor(
  name='Tag',
  full_name='repr.Tag',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='repr.Tag.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='repr.Tag.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=101,
)


_STATNAME = _descriptor.Descriptor(
  name='StatName',
  full_name='repr.StatName',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='repr.StatName.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='uniqueId', full_name='repr.StatName.uniqueId', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\342\336\037\014XXX_uniqueId\352\336\037\000'))),
    _descriptor.FieldDescriptor(
      name='uniqueIdstr', full_name='repr.StatName.uniqueIdstr', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\342\336\037\017XXX_uniqueIdstr\352\336\037\000'))),
    _descriptor.FieldDescriptor(
      name='resolution', full_name='repr.StatName.resolution', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ttl', full_name='repr.StatName.ttl', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tagMode', full_name='repr.StatName.tagMode', index=5,
      number=6, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tags', full_name='repr.StatName.tags', index=6,
      number=13, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='meta_tags', full_name='repr.StatName.meta_tags', index=7,
      number=14, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=104,
  serialized_end=333,
)


_STATREPR = _descriptor.Descriptor(
  name='StatRepr',
  full_name='repr.StatRepr',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='repr.StatRepr.name', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='time', full_name='repr.StatRepr.time', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='min', full_name='repr.StatRepr.min', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='max', full_name='repr.StatRepr.max', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='last', full_name='repr.StatRepr.last', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sum', full_name='repr.StatRepr.sum', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='count', full_name='repr.StatRepr.count', index=6,
      number=7, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=335,
  serialized_end=457,
)

_STATNAME.fields_by_name['tagMode'].enum_type = _TAGMODE
_STATNAME.fields_by_name['tags'].message_type = _TAG
_STATNAME.fields_by_name['meta_tags'].message_type = _TAG
_STATREPR.fields_by_name['name'].message_type = _STATNAME
DESCRIPTOR.message_types_by_name['Tag'] = _TAG
DESCRIPTOR.message_types_by_name['StatName'] = _STATNAME
DESCRIPTOR.message_types_by_name['StatRepr'] = _STATREPR
DESCRIPTOR.enum_types_by_name['TagMode'] = _TAGMODE

Tag = _reflection.GeneratedProtocolMessageType('Tag', (_message.Message,), dict(
  DESCRIPTOR = _TAG,
  __module__ = 'repr_pb2'
  # @@protoc_insertion_point(class_scope:repr.Tag)
  ))
_sym_db.RegisterMessage(Tag)

StatName = _reflection.GeneratedProtocolMessageType('StatName', (_message.Message,), dict(
  DESCRIPTOR = _STATNAME,
  __module__ = 'repr_pb2'
  # @@protoc_insertion_point(class_scope:repr.StatName)
  ))
_sym_db.RegisterMessage(StatName)

StatRepr = _reflection.GeneratedProtocolMessageType('StatRepr', (_message.Message,), dict(
  DESCRIPTOR = _STATREPR,
  __module__ = 'repr_pb2'
  # @@protoc_insertion_point(class_scope:repr.StatRepr)
  ))
_sym_db.RegisterMessage(StatRepr)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\310\341\036\000\300\342\036\001\320\342\036\001\310\342\036\001\340\342\036\001\370\341\036\001'))
_STATNAME.fields_by_name['uniqueId'].has_options = True
_STATNAME.fields_by_name['uniqueId']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\342\336\037\014XXX_uniqueId\352\336\037\000'))
_STATNAME.fields_by_name['uniqueIdstr'].has_options = True
_STATNAME.fields_by_name['uniqueIdstr']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\342\336\037\017XXX_uniqueIdstr\352\336\037\000'))
# @@protoc_insertion_point(module_scope)
